module.exports = {
    google:{
        clientId:'YOUR_CLIENT_ID',
        clientSecret:'YOUR_CLIENT_SECRET'
    },
    gmail:{
        username:'YOUR_EMAIL',
        password:'YOUR_PASSWORD'
    },
    jwt:{
        secret:'YOUR_JWT_SECRET'
    },
    session:{
        secret:'YOUR_SECRET_KEY'
    },
    mongodb:{
        url_string:'mongodb://localhost:27017/chatbooks'
    }
}